# Form implementation generated from reading ui file 'UIPage.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(230, 370, 561, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.verticalLayout_2.addWidget(self.label1)
        self.listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_2.addWidget(self.listWidget)
        self.pushButton1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton1.setFont(font)
        self.pushButton1.setObjectName("pushButton1")
        self.verticalLayout_2.addWidget(self.pushButton1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 801, 224))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lock = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lock.setAutoFillBackground(False)
        self.lock.setStyleSheet("QPushButton{\n"
"    border: 1px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(213, 255, 213);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 1px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 10px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.lock.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/lock.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.lock.setIcon(icon)
        self.lock.setIconSize(QtCore.QSize(100, 100))
        self.lock.setFlat(True)
        self.lock.setObjectName("lock")
        self.gridLayout_2.addWidget(self.lock, 0, 4, 1, 1)
        self.turnStudentPCOn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.turnStudentPCOn.setAutoFillBackground(False)
        self.turnStudentPCOn.setStyleSheet("QPushButton{\n"
"    border: 1px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(213, 255, 213);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 1px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 10px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.turnStudentPCOn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/switch-on.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.turnStudentPCOn.setIcon(icon1)
        self.turnStudentPCOn.setIconSize(QtCore.QSize(100, 100))
        self.turnStudentPCOn.setFlat(True)
        self.turnStudentPCOn.setObjectName("turnStudentPCOn")
        self.gridLayout_2.addWidget(self.turnStudentPCOn, 0, 1, 1, 1)
        self.watchStudentScreen = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.watchStudentScreen.setAutoFillBackground(False)
        self.watchStudentScreen.setStyleSheet("QPushButton{\n"
"    border: 1px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(213, 255, 213);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 1px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 10px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.watchStudentScreen.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/watch screen.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.watchStudentScreen.setIcon(icon2)
        self.watchStudentScreen.setIconSize(QtCore.QSize(100, 100))
        self.watchStudentScreen.setFlat(True)
        self.watchStudentScreen.setObjectName("watchStudentScreen")
        self.gridLayout_2.addWidget(self.watchStudentScreen, 0, 2, 1, 1)
        self.turnOffStudentPC = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.turnOffStudentPC.setAutoFillBackground(False)
        self.turnOffStudentPC.setStyleSheet("QPushButton{\n"
"    border: 1px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(213, 255, 213);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 1px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 10px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.turnOffStudentPC.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/switch-off.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.turnOffStudentPC.setIcon(icon3)
        self.turnOffStudentPC.setIconSize(QtCore.QSize(100, 100))
        self.turnOffStudentPC.setFlat(True)
        self.turnOffStudentPC.setObjectName("turnOffStudentPC")
        self.gridLayout_2.addWidget(self.turnOffStudentPC, 1, 1, 1, 1)
        self.stopShareScreen = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.stopShareScreen.setAutoFillBackground(False)
        self.stopShareScreen.setStyleSheet("QPushButton{\n"
"    border: 1px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(213, 255, 213);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 1px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 10px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.stopShareScreen.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/stop share screen.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.stopShareScreen.setIcon(icon4)
        self.stopShareScreen.setIconSize(QtCore.QSize(100, 100))
        self.stopShareScreen.setFlat(True)
        self.stopShareScreen.setObjectName("stopShareScreen")
        self.gridLayout_2.addWidget(self.stopShareScreen, 1, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.startShareScreen = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.startShareScreen.setAutoFillBackground(False)
        self.startShareScreen.setStyleSheet("QPushButton{\n"
"    border: 1px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(213, 255, 213);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 1px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 10px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.startShareScreen.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/share screen.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.startShareScreen.setIcon(icon5)
        self.startShareScreen.setIconSize(QtCore.QSize(100, 100))
        self.startShareScreen.setFlat(True)
        self.startShareScreen.setObjectName("startShareScreen")
        self.gridLayout_2.addWidget(self.startShareScreen, 0, 3, 1, 1)
        self.unlock = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.unlock.setAutoFillBackground(False)
        self.unlock.setStyleSheet("QPushButton{\n"
"    border: 1px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(213, 255, 213);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 1px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 10px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.unlock.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/unlock.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.unlock.setIcon(icon6)
        self.unlock.setIconSize(QtCore.QSize(100, 100))
        self.unlock.setFlat(True)
        self.unlock.setObjectName("unlock")
        self.gridLayout_2.addWidget(self.unlock, 1, 4, 1, 1)
        self.sendFile = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sendFile.setAutoFillBackground(False)
        self.sendFile.setStyleSheet("QPushButton{\n"
"    border: 1px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(213, 255, 213);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 1px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 10px solid rgb(0, 255, 127);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.sendFile.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("res/send-file.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.sendFile.setIcon(icon7)
        self.sendFile.setIconSize(QtCore.QSize(100, 100))
        self.sendFile.setFlat(True)
        self.sendFile.setObjectName("sendFile")
        self.gridLayout_2.addWidget(self.sendFile, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(17, 17, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 5, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label1.setText(_translate("MainWindow", "users list"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "user1"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "user2"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "user3"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton1.setText(_translate("MainWindow", "select all users"))
