# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import res.imgs_rc
import uiActions
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, server):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(230, 370, 561, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.verticalLayout_2.addWidget(self.label1)
        self.usersList = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.usersList.setSelectionMode(
            QtWidgets.QAbstractItemView.ExtendedSelection)
        self.usersList.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.usersList.setObjectName("usersList")
        self.verticalLayout_2.addWidget(self.usersList)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.checkBox.setFont(font)
        self.checkBox.setAutoFillBackground(False)
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-11, -1, 811, 371))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lock = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.lock.setAutoFillBackground(False)
        self.lock.setStyleSheet("QPushButton{\n"
                                "    border: 1px solid rgb(0, 255, 127);\n"
                                "    border-radius: 20px;\n"
                                "    background-color: rgb(213, 255, 213);\n"
                                "}\n"
                                "QPushButton:hover{\n"
                                "    border: 1px solid rgb(0, 255, 127);\n"
                                "    border-radius: 20px;\n"
                                "    background-color: rgb(0, 170, 0);\n"
                                "}\n"
                                "\n"
                                "QPushButton:pressed{\n"
                                "    border: 10px solid rgb(0, 255, 127);\n"
                                "    border-radius: 20px;\n"
                                "    background-color: rgb(0, 170, 0);\n"
                                "}\n"
                                "")
        self.lock.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/lock.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lock.setIcon(icon)
        self.lock.setIconSize(QtCore.QSize(100, 100))
        self.lock.setFlat(True)
        self.lock.setObjectName("lock")
        self.gridLayout_2.addWidget(self.lock, 0, 3, 1, 1)
        self.startShareScreen = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.startShareScreen.setAutoFillBackground(False)
        self.startShareScreen.setStyleSheet("QPushButton{\n"
                                            "    border: 1px solid rgb(0, 255, 127);\n"
                                            "    border-radius: 20px;\n"
                                            "    background-color: rgb(213, 255, 213);\n"
                                            "}\n"
                                            "QPushButton:hover{\n"
                                            "    border: 1px solid rgb(0, 255, 127);\n"
                                            "    border-radius: 20px;\n"
                                            "    background-color: rgb(0, 170, 0);\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:pressed{\n"
                                            "    border: 10px solid rgb(0, 255, 127);\n"
                                            "    border-radius: 20px;\n"
                                            "    background-color: rgb(0, 170, 0);\n"
                                            "}\n"
                                            "")
        self.startShareScreen.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/share screen.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startShareScreen.setIcon(icon1)
        self.startShareScreen.setIconSize(QtCore.QSize(100, 100))
        self.startShareScreen.setFlat(True)
        self.startShareScreen.setObjectName("startShareScreen")
        self.gridLayout_2.addWidget(self.startShareScreen, 0, 2, 1, 1)
        self.unlock = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.unlock.setAutoFillBackground(False)
        self.unlock.setStyleSheet("QPushButton{\n"
                                  "    border: 1px solid rgb(0, 255, 127);\n"
                                  "    border-radius: 20px;\n"
                                  "    background-color: rgb(213, 255, 213);\n"
                                  "}\n"
                                  "QPushButton:hover{\n"
                                  "    border: 1px solid rgb(0, 255, 127);\n"
                                  "    border-radius: 20px;\n"
                                  "    background-color: rgb(0, 170, 0);\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:pressed{\n"
                                  "    border: 10px solid rgb(0, 255, 127);\n"
                                  "    border-radius: 20px;\n"
                                  "    background-color: rgb(0, 170, 0);\n"
                                  "}\n"
                                  "")
        self.unlock.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/unlock.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.unlock.setIcon(icon2)
        self.unlock.setIconSize(QtCore.QSize(100, 100))
        self.unlock.setFlat(True)
        self.unlock.setObjectName("unlock")
        self.gridLayout_2.addWidget(self.unlock, 1, 3, 1, 1)
        self.stopShareScreen = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.stopShareScreen.setAutoFillBackground(False)
        self.stopShareScreen.setStyleSheet("QPushButton{\n"
                                           "    border: 1px solid rgb(0, 255, 127);\n"
                                           "    border-radius: 20px;\n"
                                           "    background-color: rgb(213, 255, 213);\n"
                                           "}\n"
                                           "QPushButton:hover{\n"
                                           "    border: 1px solid rgb(0, 255, 127);\n"
                                           "    border-radius: 20px;\n"
                                           "    background-color: rgb(0, 170, 0);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:pressed{\n"
                                           "    border: 10px solid rgb(0, 255, 127);\n"
                                           "    border-radius: 20px;\n"
                                           "    background-color: rgb(0, 170, 0);\n"
                                           "}\n"
                                           "")
        self.stopShareScreen.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(
            ":/newPrefix/stop share screen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopShareScreen.setIcon(icon3)
        self.stopShareScreen.setIconSize(QtCore.QSize(100, 100))
        self.stopShareScreen.setFlat(True)
        self.stopShareScreen.setObjectName("stopShareScreen")
        self.gridLayout_2.addWidget(self.stopShareScreen, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(
            10, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        self.watchStudentScreen = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.watchStudentScreen.setAutoFillBackground(False)
        self.watchStudentScreen.setStyleSheet("QPushButton{\n"
                                              "    border: 1px solid rgb(0, 255, 127);\n"
                                              "    border-radius: 20px;\n"
                                              "    background-color: rgb(213, 255, 213);\n"
                                              "}\n"
                                              "QPushButton:hover{\n"
                                              "    border: 1px solid rgb(0, 255, 127);\n"
                                              "    border-radius: 20px;\n"
                                              "    background-color: rgb(0, 170, 0);\n"
                                              "}\n"
                                              "\n"
                                              "QPushButton:pressed{\n"
                                              "    border: 10px solid rgb(0, 255, 127);\n"
                                              "    border-radius: 20px;\n"
                                              "    background-color: rgb(0, 170, 0);\n"
                                              "}\n"
                                              "")
        self.watchStudentScreen.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/watch screen.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.watchStudentScreen.setIcon(icon4)
        self.watchStudentScreen.setIconSize(QtCore.QSize(100, 100))
        self.watchStudentScreen.setFlat(True)
        self.watchStudentScreen.setObjectName("watchStudentScreen")
        self.gridLayout_2.addWidget(self.watchStudentScreen, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        uiActions.buttons_actions(self.lock, self.startShareScreen, self.stopShareScreen,
                                  self.unlock, self.watchStudentScreen, self.checkBox, self.usersList, server)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label1.setText(_translate("MainWindow", "users list"))
        self.usersList.setSortingEnabled(False)
        self.checkBox.setText(_translate("MainWindow", "select all users"))
